export const NavItems = [
    {
        label:"Home",
        to:"/"
    },
    {
        label:"Products",
        to:"/products"
    },
    {
        label:"Services",
        to:"/services"
    },
    {
        label:"About",
        to:"/about"
    },
    {
        label:"Gallary",
        to:"/gallary"
    },
]